name: farmaprecios
description: "Consulte la información de su producto en segundos."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.2.0
  shared_preferences: ^2.2.2
  lottie: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_beep: ^1.0.0
  connectivity: ^3.0.6
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets: 
    - assets/lottie/
    - assets/images/
